### ISSUE TITLE
stb framework

### ISSUE THREAD

**Issue by DarkPark** [immosmart/smartbox#74]
it may be interesting for you to take a look at this project - https://github.com/DarkPark/stb
and the demo - https://www.npmjs.org/package/stb-demo

**Comment by DenisChinin** [comment]
Ok, i will submit my questions in your repository

**Comment by paunin** [comment]
@DarkPark , broken link

**Comment by DarkPark** [comment]
thanks
correct link - https://github.com/DarkPark/stb-demo
