### ISSUE TITLE
некорректное получение модели устройства на LG

### ISSUE THREAD

**Issue by solntcev** [immosmart/smartbox#75]
platforms/lg/sb.platform.lg.js 
для единообразия с самсунгом нужно заменить

        this.productCode = this.device.platform;

на

        this.productCode = this.device.modelName;

**Comment by PLoginoff** [comment]
@solntcev Иван, можете сделать пул реквест?

**Comment by solntcev** [comment]
https://github.com/immosmart/smartbox/pull/77
