### ISSUE TITLE
Помогите с меню

### ISSUE THREAD

**Issue by lepriconl** [immosmart/smartbox#79]
В списке видео, добавляю 50 видео файлов, на экране отображаются 30, когда пультом спускаюсь вниз по списку, курсор выходит за экран, видео он выбирает, но курсора не видно. Подскажите как исправить. И второй вопрос, Видео включается, все работает отлично, но меню не пропадает, подскажите пожалуйста как сделать так, чтобы меню убиралось при проигрывании видео и вызвалось по нажатию какой то кнопки. Заранее спасибо.

**Comment by GubanovAnton** [comment]
Клавиша A должна убирать меню. А вот со списком тоже проблема. Всего 16 каналов в списке отображается, а ниже бегунок не ходит.
